arch: mobilenet # MobileNet V1
widen_factor: 0.5
checkpoint_fp: pose_estimation_utils/weights/mb05_120x120.pth
bfm_fp: pose_estimation_utils/configs/bfm_noneck_v3.pkl # or configs/bfm_noneck_v3_slim.pkl
size: 120
num_params: 62
